# Generated by Django 6.0.3 on 2026-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='approved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
