# Generated by Django 6.0.3 on 2026-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_labrequest_approved_quantity_alter_labrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='packages',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 1L, 100 tablets', max_length=100, null=True),
        ),
    ]
